version: '2'

services:
  web:
    build: web
    image: registry.cn-hangzhou.aliyuncs.com/firesh/lab-web
    volumes: ["./web/static:/usr/share/nginx/html"]
    ports: ["80:80"]

  words:
    build: words-dispatcher
    image: registry.cn-hangzhou.aliyuncs.com/iresh/lab-words-dispatcher

  words-java:
    build: words-java
    image: registry.cn-hangzhou.aliyuncs.com/firesh/lab-words-java
    #ports: ["5005:5005"]

  mongo:
    image: mongo:3.3.8
